from enum import Enum


class EventType(str, Enum):
    CHOKEPOINT_DISRUPTION = "CHOKEPOINT_DISRUPTION"
    CANAL_CLOSURE = "CANAL_CLOSURE"
    CARRIER_REROUTING = "CARRIER_REROUTING"
    PORT_STRIKE = "PORT_STRIKE"
    PORT_DISRUPTION = "PORT_DISRUPTION"
    SEVERE_WEATHER = "SEVERE_WEATHER"
    SECURITY_INCIDENT = "SECURITY_INCIDENT"
    TRADE_RESTRICTION = "TRADE_RESTRICTION"
    SANCTIONS = "SANCTIONS"
    PIRACY = "PIRACY"
    OTHER = "OTHER"


class EventStatus(str, Enum):
    MONITORING = "MONITORING"
    ACTIVE = "ACTIVE"
    ESCALATING = "ESCALATING"
    STABILISING = "STABILISING"
    RESOLVED = "RESOLVED"
    ARCHIVED = "ARCHIVED"


class Severity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
